name: 'Terraform VM Creation workflow'

on:
  push:
    branches:
      - main
      - newfeature
  pull_request:
    branches:
      - main

jobs:
  terraformfile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: v1.3.4

      - name: Azure Logins
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
        
      - name: Terraform Init
        run: terraform init
  
      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve
        
      # - name: Terraform destroy
      #   if: github.event_name == 'workflow_dispatch'
      #   run: terraform destroy -auto-approve
